### ISSUE TITLE
States should be array exception

### ISSUE THREAD

**Issue by TheUnlimited64** [fiskaly/fiskaly-sdk-php#4]
I'm trying to make responses, but if the state has to be array I can't make it work. My Code is the following:

```php
$query = new stdClass();
$query->states = array("FINISHED")
```
If I now pass it to the `response()` method then I get the exception state should be an array.

Im passing `$query` in the `$query` parameter of the method (not converted to JSON or something like that).

**Comment by prempador** [comment]
Hello @Gamestarplayer41, 

Thank you for your issue. We are aware that there is still some weird behavior with the query param and arrays. We are currently working on a fix.
